export * from '../component/home-page/home-page.component'
export *from '../component/login/login.component'
export * from '../component/page-not-found/page-not-found.component'
export * from '../component/view-acquisition/view-acquisition.component'
export * from '../component/view-category/view-category.component'
export *from '../component/view-department/view-department.component'
export * from '../component/view-item-list/view-item-list.component'
export * from '../component/view-subcategory/view-subcategory.component'